### ISSUE TITLE
Consider tracks in the snap store

### ISSUE THREAD

**Issue by popey** [DownThePark/mysql-snap#1]
Thanks for making this snap. Nice idea!

Have you considered using the "tracks" functionality to enable multiple different versions of the same snap to be published?

That way, someone could stay on the 8.0 LTS release of MySQL or opt for the newer 8.2 or 8.3 releases. 

This could be achieved with separate branches on the git repo and GitHub actions to do the build and push to the store. The [snapcrafters](https://github.com/snapcrafters) repo has some examples of this, like (most recently) the [sublime-text](https://github.com/snapcrafters/sublime-text) snap, which has a "dev" track as well as the "latest" one.

**Comment by DownThePark** [comment]
Hey @popey ,

Thanks for the suggestion! Using tracks is a great idea, I'll open a request to enable an "[innovation](https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/)" track on the Snapcraft forum.

**Comment by DownThePark** [comment]
Hi, instead of my previously proposed `innovation` track, the latest release of MySQL is now available via the `latest` track, while the current LTS release is available via the `8.0` track (which is also the default track). Builds are currently underway for this snap. Thanks again for your suggestion!
